.nh
.TH "GH-CACHE" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-cache - Manage Github Actions caches


.SH SYNOPSIS
.PP
\fB\fCgh cache <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with Github Actions caches.


.SH AVAILABLE COMMANDS
.TP
\fB\fCgh-cache-delete(1)\fR
Delete Github Actions caches

.TP
\fB\fCgh-cache-list(1)\fR
List Github Actions caches


.SH OPTIONS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH EXAMPLE
.PP
.RS

.nf
$ gh cache list
$ gh cache delete --all


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
