.nh
.TH "GH-CONFIG-CLEAR-CACHE" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-config-clear-cache - Clear the cli cache


.SH SYNOPSIS
.PP
\fB\fCgh config clear-cache [flags]\fR


.SH EXAMPLE
.PP
.RS

.nf
# Clear the cli cache
$ gh config clear-cache


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-config(1)\fR
