.nh
.TH "GH-GIST-RENAME" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-gist-rename - Rename a file in a gist


.SH SYNOPSIS
.PP
\fB\fCgh gist rename {<id> | <url>} <oldFilename> <newFilename> [flags]\fR


.SH DESCRIPTION
.PP
Rename a file in the given gist ID / URL.


.SH SEE ALSO
.PP
\fB\fCgh-gist(1)\fR
