.nh
.TH "GH-ORG" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-org - Manage organizations


.SH SYNOPSIS
.PP
\fB\fCgh org <command> [flags]\fR


.SH DESCRIPTION
.PP
Work with Github organizations.


.SH GENERAL COMMANDS
.TP
\fB\fCgh-org-list(1)\fR
List organizations for the authenticated user.


.SH EXAMPLE
.PP
.RS

.nf
$ gh org list


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh(1)\fR
