.nh
.TH "GH-PROJECT-DELETE" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-delete - Delete a project


.SH SYNOPSIS
.PP
\fB\fCgh project delete [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC--owner\fR \fB\fC<string>\fR
Login of the owner. Use "@me" for the current user.


.SH EXAMPLE
.PP
.RS

.nf
# delete the current user's project "1"
gh project delete 1 --owner "@me"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
