.nh
.TH "GH-PROJECT-FIELD-LIST" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-field-list - List the fields in a project


.SH SYNOPSIS
.PP
\fB\fCgh project field-list number [flags]\fR


.SH OPTIONS
.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of fields to fetch

.TP
\fB\fC--owner\fR \fB\fC<string>\fR
Login of the owner. Use "@me" for the current user.


.SH EXAMPLE
.PP
.RS

.nf
# list fields in the current user's project "1"
gh project field-list 1 --owner "@me"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
