.nh
.TH "GH-PROJECT-FIELD-DELETE" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-field-delete - Delete a field in a project


.SH SYNOPSIS
.PP
\fB\fCgh project field-delete [flags]\fR


.SH OPTIONS
.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC--id\fR \fB\fC<string>\fR
ID of the field to delete


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
