.nh
.TH "GH-PROJECT-ITEM-EDIT" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-item-edit - Edit an item in a project


.SH SYNOPSIS
.PP
\fB\fCgh project item-edit [flags]\fR


.SH DESCRIPTION
.PP
Edit either a draft issue or a project item. Both usages require the ID of the item to edit.

.PP
For non-draft issues, the ID of the project is also required, and only a single field value can be updated per invocation.

.PP
Remove project item field value using "--clear" flag.


.SH OPTIONS
.TP
\fB\fC--body\fR \fB\fC<string>\fR
Body of the draft issue item

.TP
\fB\fC--clear\fR
Remove field value

.TP
\fB\fC--date\fR \fB\fC<string>\fR
Date value for the field (YYYY-MM-DD)

.TP
\fB\fC--field-id\fR \fB\fC<string>\fR
ID of the field to update

.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC--id\fR \fB\fC<string>\fR
ID of the item to edit

.TP
\fB\fC--iteration-id\fR \fB\fC<string>\fR
ID of the iteration value to set on the field

.TP
\fB\fC--number\fR \fB\fC<float32>\fR
Number value for the field

.TP
\fB\fC--project-id\fR \fB\fC<string>\fR
ID of the project to which the field belongs to

.TP
\fB\fC--single-select-option-id\fR \fB\fC<string>\fR
ID of the single select option value to set on the field

.TP
\fB\fC--text\fR \fB\fC<string>\fR
Text value for the field

.TP
\fB\fC--title\fR \fB\fC<string>\fR
Title of the draft issue item


.SH EXAMPLE
.PP
.RS

.nf
# edit an item's text field value
gh project item-edit --id <item-ID> --field-id <field-ID> --project-id <project-ID> --text "new text"

# clear an item's field value
gh project item-edit --id <item-ID> --field-id <field-ID> --project-id <project-ID> --clear


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
