.nh
.TH "GH-PROJECT-LIST" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-list - List the projects for an owner


.SH SYNOPSIS
.PP
\fB\fCgh project list [flags]\fR


.SH OPTIONS
.TP
\fB\fC--closed\fR
Include closed projects

.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of projects to fetch

.TP
\fB\fC--owner\fR \fB\fC<string>\fR
Login of the owner

.TP
\fB\fC-w\fR, \fB\fC--web\fR
Open projects list in the browser


.SH EXAMPLE
.PP
.RS

.nf
# list the current user's projects
gh project list

# list the projects for org github including closed projects
gh project list --owner github --closed


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
