.nh
.TH "GH-PROJECT-FIELD-CREATE" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-field-create - Create a field in a project


.SH SYNOPSIS
.PP
\fB\fCgh project field-create [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB\fC--data-type\fR \fB\fC<string>\fR
DataType of the new field.: {TEXT|SINGLE_SELECT|DATE|NUMBER}

.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC--name\fR \fB\fC<string>\fR
Name of the new field

.TP
\fB\fC--owner\fR \fB\fC<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB\fC--single-select-options\fR \fB\fC<strings>\fR
Options for SINGLE_SELECT data type


.SH EXAMPLE
.PP
.RS

.nf
# create a field in the current user's project "1"
gh project field-create 1 --owner "@me" --name "new field" --data-type "text"

# create a field with three options to select from for owner monalisa
gh project field-create 1 --owner monalisa --name "new field" --data-type "SINGLE_SELECT" --single-select-options "one,two,three"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
