.nh
.TH "GH-PROJECT-EDIT" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-project-edit - Edit a project


.SH SYNOPSIS
.PP
\fB\fCgh project edit [<number>] [flags]\fR


.SH OPTIONS
.TP
\fB\fC-d\fR, \fB\fC--description\fR \fB\fC<string>\fR
New description of the project

.TP
\fB\fC--format\fR \fB\fC<string>\fR
Output format: {json}

.TP
\fB\fC--owner\fR \fB\fC<string>\fR
Login of the owner. Use "@me" for the current user.

.TP
\fB\fC--readme\fR \fB\fC<string>\fR
New readme for the project

.TP
\fB\fC--title\fR \fB\fC<string>\fR
New title for the project

.TP
\fB\fC--visibility\fR \fB\fC<string>\fR
Change project visibility: {PUBLIC|PRIVATE}


.SH EXAMPLE
.PP
.RS

.nf
# edit the title of monalisa's project "1"
gh project edit 1 --owner monalisa --title "New title"


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-project(1)\fR
