.nh
.TH "GH-SEARCH-CODE" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-search-code - Search within code


.SH SYNOPSIS
.PP
\fB\fCgh search code <query> [flags]\fR


.SH DESCRIPTION
.PP
Search within code in GitHub repositories.

.PP
The search syntax is documented at:
https://docs.github.com/search-github/searching-on-github/searching-code
\[la]https://docs.github.com/search-github/searching-on-github/searching-code\[ra]

.PP
Note that these search results are powered by what is now a legacy GitHub code search engine.
The results might not match what is seen on GitHub.com, and new features like regex search
are not yet available via the GitHub API.


.SH OPTIONS
.TP
\fB\fC--extension\fR \fB\fC<string>\fR
Filter on file extension

.TP
\fB\fC--filename\fR \fB\fC<string>\fR
Filter on filename

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC--language\fR \fB\fC<string>\fR
Filter results by language

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of code results to fetch

.TP
\fB\fC--match\fR \fB\fC<strings>\fR
Restrict search to file contents or file path: {file|path}

.TP
\fB\fC--owner\fR \fB\fC<strings>\fR
Filter on owner

.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<strings>\fR
Filter on repository

.TP
\fB\fC--size\fR \fB\fC<string>\fR
Filter on size range, in kilobytes

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template; see "gh help formatting"

.TP
\fB\fC-w\fR, \fB\fC--web\fR
Open the search query in the web browser


.SH EXAMPLE
.PP
.RS

.nf
# search code matching "react" and "lifecycle"
$ gh search code react lifecycle

# search code matching "error handling" 
$ gh search code "error handling"
	
# search code matching "deque" in Python files
$ gh search code deque --language=python

# search code matching "cli" in repositories owned by microsoft organization
$ gh search code cli --owner=microsoft

# search code matching "panic" in the GitHub CLI repository
$ gh search code panic --repo cli/cli

# search code matching keyword "lint" in package.json files
$ gh search code lint --filename package.json


.fi
.RE


.SH SEE ALSO
.PP
\fB\fCgh-search(1)\fR
