.nh
.TH "GH-WORKFLOW-LIST" "1" "Oct 2023" "GitHub CLI 2.37.0" "GitHub CLI manual"

.SH NAME
.PP
gh-workflow-list - List workflows


.SH SYNOPSIS
.PP
\fB\fCgh workflow list [flags]\fR


.SH DESCRIPTION
.PP
List workflow files, hiding disabled workflows by default.


.SH OPTIONS
.TP
\fB\fC-a\fR, \fB\fC--all\fR
Include disabled workflows

.TP
\fB\fC-q\fR, \fB\fC--jq\fR \fB\fC<expression>\fR
Filter JSON output using a jq expression

.TP
\fB\fC--json\fR \fB\fC<fields>\fR
Output JSON with the specified fields

.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of workflows to fetch

.TP
\fB\fC-t\fR, \fB\fC--template\fR \fB\fC<string>\fR
Format JSON output using a Go template; see "gh help formatting"


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-workflow(1)\fR
